/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTrackingIndexRouteImport } from './routes/_authenticated/tracking/index'
import { Route as AuthenticatedTourPackagesIndexRouteImport } from './routes/_authenticated/tour-packages/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReviewsIndexRouteImport } from './routes/_authenticated/reviews/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGuidesIndexRouteImport } from './routes/_authenticated/guides/index'
import { Route as AuthenticatedGalleryIndexRouteImport } from './routes/_authenticated/gallery/index'
import { Route as AuthenticatedDestinationsIndexRouteImport } from './routes/_authenticated/destinations/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCarRentalIndexRouteImport } from './routes/_authenticated/car-rental/index'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated/calendar/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as AuthenticatedBlogIndexRouteImport } from './routes/_authenticated/blog/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedUsersTourGuidesRouteImport } from './routes/_authenticated/users/tour-guides'
import { Route as AuthenticatedUsersStaffRouteImport } from './routes/_authenticated/users/staff'
import { Route as AuthenticatedUsersCustomersRouteImport } from './routes/_authenticated/users/customers'
import { Route as AuthenticatedTourPackagesNewRouteImport } from './routes/_authenticated/tour-packages/new'
import { Route as AuthenticatedTourPackagesItinerariesRouteImport } from './routes/_authenticated/tour-packages/itineraries'
import { Route as AuthenticatedTourPackagesCategoriesRouteImport } from './routes/_authenticated/tour-packages/categories'
import { Route as AuthenticatedSettingsSocialRouteImport } from './routes/_authenticated/settings/social'
import { Route as AuthenticatedSettingsSeoRouteImport } from './routes/_authenticated/settings/seo'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsContentRouteImport } from './routes/_authenticated/settings/content'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSecurityRolesRouteImport } from './routes/_authenticated/security/roles'
import { Route as AuthenticatedSecurityActivityRouteImport } from './routes/_authenticated/security/activity'
import { Route as AuthenticatedReviewsPendingRouteImport } from './routes/_authenticated/reviews/pending'
import { Route as AuthenticatedReportsRevenueRouteImport } from './routes/_authenticated/reports/revenue'
import { Route as AuthenticatedReportsBookingsRouteImport } from './routes/_authenticated/reports/bookings'
import { Route as AuthenticatedReportsAnalyticsRouteImport } from './routes/_authenticated/reports/analytics'
import { Route as AuthenticatedPaymentsTransactionsRouteImport } from './routes/_authenticated/payments/transactions'
import { Route as AuthenticatedPaymentsStatusRouteImport } from './routes/_authenticated/payments/status'
import { Route as AuthenticatedPaymentsRefundsRouteImport } from './routes/_authenticated/payments/refunds'
import { Route as AuthenticatedMessagesInquiriesRouteImport } from './routes/_authenticated/messages/inquiries'
import { Route as AuthenticatedMessagesContactRouteImport } from './routes/_authenticated/messages/contact'
import { Route as AuthenticatedGuidesAvailabilityRouteImport } from './routes/_authenticated/guides/availability'
import { Route as AuthenticatedGuidesAssignRouteImport } from './routes/_authenticated/guides/assign'
import { Route as AuthenticatedGalleryUploadRouteImport } from './routes/_authenticated/gallery/upload'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDestinationsNewRouteImport } from './routes/_authenticated/destinations/new'
import { Route as AuthenticatedCarRentalPendingRouteImport } from './routes/_authenticated/car-rental/pending'
import { Route as AuthenticatedBookingsPendingRouteImport } from './routes/_authenticated/bookings/pending'
import { Route as AuthenticatedBookingsConfirmedRouteImport } from './routes/_authenticated/bookings/confirmed'
import { Route as AuthenticatedBookingsCancelledRouteImport } from './routes/_authenticated/bookings/cancelled'
import { Route as AuthenticatedBlogNewRouteImport } from './routes/_authenticated/blog/new'
import { Route as AuthenticatedBlogCategoriesRouteImport } from './routes/_authenticated/blog/categories'
import { Route as AuthenticatedCarRentalVehiclesIndexRouteImport } from './routes/_authenticated/car-rental/vehicles/index'
import { Route as AuthenticatedCarRentalVehiclesNewRouteImport } from './routes/_authenticated/car-rental/vehicles/new'
import { Route as AuthenticatedCarRentalVehiclesVehicleIdRouteImport } from './routes/_authenticated/car-rental/vehicles/$vehicleId'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackingIndexRoute =
  AuthenticatedTrackingIndexRouteImport.update({
    id: '/tracking/',
    path: '/tracking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTourPackagesIndexRoute =
  AuthenticatedTourPackagesIndexRouteImport.update({
    id: '/tour-packages/',
    path: '/tour-packages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReviewsIndexRoute =
  AuthenticatedReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuidesIndexRoute =
  AuthenticatedGuidesIndexRouteImport.update({
    id: '/guides/',
    path: '/guides/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGalleryIndexRoute =
  AuthenticatedGalleryIndexRouteImport.update({
    id: '/gallery/',
    path: '/gallery/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestinationsIndexRoute =
  AuthenticatedDestinationsIndexRouteImport.update({
    id: '/destinations/',
    path: '/destinations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarRentalIndexRoute =
  AuthenticatedCarRentalIndexRouteImport.update({
    id: '/car-rental/',
    path: '/car-rental/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlogIndexRoute = AuthenticatedBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedUsersTourGuidesRoute =
  AuthenticatedUsersTourGuidesRouteImport.update({
    id: '/users/tour-guides',
    path: '/users/tour-guides',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersStaffRoute = AuthenticatedUsersStaffRouteImport.update({
  id: '/users/staff',
  path: '/users/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersCustomersRoute =
  AuthenticatedUsersCustomersRouteImport.update({
    id: '/users/customers',
    path: '/users/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTourPackagesNewRoute =
  AuthenticatedTourPackagesNewRouteImport.update({
    id: '/tour-packages/new',
    path: '/tour-packages/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTourPackagesItinerariesRoute =
  AuthenticatedTourPackagesItinerariesRouteImport.update({
    id: '/tour-packages/itineraries',
    path: '/tour-packages/itineraries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTourPackagesCategoriesRoute =
  AuthenticatedTourPackagesCategoriesRouteImport.update({
    id: '/tour-packages/categories',
    path: '/tour-packages/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSocialRoute =
  AuthenticatedSettingsSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSeoRoute =
  AuthenticatedSettingsSeoRouteImport.update({
    id: '/seo',
    path: '/seo',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsContentRoute =
  AuthenticatedSettingsContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSecurityRolesRoute =
  AuthenticatedSecurityRolesRouteImport.update({
    id: '/security/roles',
    path: '/security/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecurityActivityRoute =
  AuthenticatedSecurityActivityRouteImport.update({
    id: '/security/activity',
    path: '/security/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewsPendingRoute =
  AuthenticatedReviewsPendingRouteImport.update({
    id: '/reviews/pending',
    path: '/reviews/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRevenueRoute =
  AuthenticatedReportsRevenueRouteImport.update({
    id: '/reports/revenue',
    path: '/reports/revenue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsBookingsRoute =
  AuthenticatedReportsBookingsRouteImport.update({
    id: '/reports/bookings',
    path: '/reports/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAnalyticsRoute =
  AuthenticatedReportsAnalyticsRouteImport.update({
    id: '/reports/analytics',
    path: '/reports/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsTransactionsRoute =
  AuthenticatedPaymentsTransactionsRouteImport.update({
    id: '/payments/transactions',
    path: '/payments/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsStatusRoute =
  AuthenticatedPaymentsStatusRouteImport.update({
    id: '/payments/status',
    path: '/payments/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRefundsRoute =
  AuthenticatedPaymentsRefundsRouteImport.update({
    id: '/payments/refunds',
    path: '/payments/refunds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesInquiriesRoute =
  AuthenticatedMessagesInquiriesRouteImport.update({
    id: '/messages/inquiries',
    path: '/messages/inquiries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesContactRoute =
  AuthenticatedMessagesContactRouteImport.update({
    id: '/messages/contact',
    path: '/messages/contact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuidesAvailabilityRoute =
  AuthenticatedGuidesAvailabilityRouteImport.update({
    id: '/guides/availability',
    path: '/guides/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuidesAssignRoute =
  AuthenticatedGuidesAssignRouteImport.update({
    id: '/guides/assign',
    path: '/guides/assign',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGalleryUploadRoute =
  AuthenticatedGalleryUploadRouteImport.update({
    id: '/gallery/upload',
    path: '/gallery/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDestinationsNewRoute =
  AuthenticatedDestinationsNewRouteImport.update({
    id: '/destinations/new',
    path: '/destinations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarRentalPendingRoute =
  AuthenticatedCarRentalPendingRouteImport.update({
    id: '/car-rental/pending',
    path: '/car-rental/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsPendingRoute =
  AuthenticatedBookingsPendingRouteImport.update({
    id: '/bookings/pending',
    path: '/bookings/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsConfirmedRoute =
  AuthenticatedBookingsConfirmedRouteImport.update({
    id: '/bookings/confirmed',
    path: '/bookings/confirmed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsCancelledRoute =
  AuthenticatedBookingsCancelledRouteImport.update({
    id: '/bookings/cancelled',
    path: '/bookings/cancelled',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlogNewRoute = AuthenticatedBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlogCategoriesRoute =
  AuthenticatedBlogCategoriesRouteImport.update({
    id: '/blog/categories',
    path: '/blog/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarRentalVehiclesIndexRoute =
  AuthenticatedCarRentalVehiclesIndexRouteImport.update({
    id: '/car-rental/vehicles/',
    path: '/car-rental/vehicles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarRentalVehiclesNewRoute =
  AuthenticatedCarRentalVehiclesNewRouteImport.update({
    id: '/car-rental/vehicles/new',
    path: '/car-rental/vehicles/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarRentalVehiclesVehicleIdRoute =
  AuthenticatedCarRentalVehiclesVehicleIdRouteImport.update({
    id: '/car-rental/vehicles/$vehicleId',
    path: '/car-rental/vehicles/$vehicleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/$': typeof AuthenticatedSplatRoute
  '/blog/categories': typeof AuthenticatedBlogCategoriesRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/bookings/cancelled': typeof AuthenticatedBookingsCancelledRoute
  '/bookings/confirmed': typeof AuthenticatedBookingsConfirmedRoute
  '/bookings/pending': typeof AuthenticatedBookingsPendingRoute
  '/car-rental/pending': typeof AuthenticatedCarRentalPendingRoute
  '/destinations/new': typeof AuthenticatedDestinationsNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/gallery/upload': typeof AuthenticatedGalleryUploadRoute
  '/guides/assign': typeof AuthenticatedGuidesAssignRoute
  '/guides/availability': typeof AuthenticatedGuidesAvailabilityRoute
  '/messages/contact': typeof AuthenticatedMessagesContactRoute
  '/messages/inquiries': typeof AuthenticatedMessagesInquiriesRoute
  '/payments/refunds': typeof AuthenticatedPaymentsRefundsRoute
  '/payments/status': typeof AuthenticatedPaymentsStatusRoute
  '/payments/transactions': typeof AuthenticatedPaymentsTransactionsRoute
  '/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/reports/bookings': typeof AuthenticatedReportsBookingsRoute
  '/reports/revenue': typeof AuthenticatedReportsRevenueRoute
  '/reviews/pending': typeof AuthenticatedReviewsPendingRoute
  '/security/activity': typeof AuthenticatedSecurityActivityRoute
  '/security/roles': typeof AuthenticatedSecurityRolesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/content': typeof AuthenticatedSettingsContentRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/seo': typeof AuthenticatedSettingsSeoRoute
  '/settings/social': typeof AuthenticatedSettingsSocialRoute
  '/tour-packages/categories': typeof AuthenticatedTourPackagesCategoriesRoute
  '/tour-packages/itineraries': typeof AuthenticatedTourPackagesItinerariesRoute
  '/tour-packages/new': typeof AuthenticatedTourPackagesNewRoute
  '/users/customers': typeof AuthenticatedUsersCustomersRoute
  '/users/staff': typeof AuthenticatedUsersStaffRoute
  '/users/tour-guides': typeof AuthenticatedUsersTourGuidesRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/blog/': typeof AuthenticatedBlogIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/car-rental/': typeof AuthenticatedCarRentalIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/gallery/': typeof AuthenticatedGalleryIndexRoute
  '/guides/': typeof AuthenticatedGuidesIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/tour-packages/': typeof AuthenticatedTourPackagesIndexRoute
  '/tracking/': typeof AuthenticatedTrackingIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/car-rental/vehicles/$vehicleId': typeof AuthenticatedCarRentalVehiclesVehicleIdRoute
  '/car-rental/vehicles/new': typeof AuthenticatedCarRentalVehiclesNewRoute
  '/car-rental/vehicles/': typeof AuthenticatedCarRentalVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/$': typeof AuthenticatedSplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/blog/categories': typeof AuthenticatedBlogCategoriesRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/bookings/cancelled': typeof AuthenticatedBookingsCancelledRoute
  '/bookings/confirmed': typeof AuthenticatedBookingsConfirmedRoute
  '/bookings/pending': typeof AuthenticatedBookingsPendingRoute
  '/car-rental/pending': typeof AuthenticatedCarRentalPendingRoute
  '/destinations/new': typeof AuthenticatedDestinationsNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/gallery/upload': typeof AuthenticatedGalleryUploadRoute
  '/guides/assign': typeof AuthenticatedGuidesAssignRoute
  '/guides/availability': typeof AuthenticatedGuidesAvailabilityRoute
  '/messages/contact': typeof AuthenticatedMessagesContactRoute
  '/messages/inquiries': typeof AuthenticatedMessagesInquiriesRoute
  '/payments/refunds': typeof AuthenticatedPaymentsRefundsRoute
  '/payments/status': typeof AuthenticatedPaymentsStatusRoute
  '/payments/transactions': typeof AuthenticatedPaymentsTransactionsRoute
  '/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/reports/bookings': typeof AuthenticatedReportsBookingsRoute
  '/reports/revenue': typeof AuthenticatedReportsRevenueRoute
  '/reviews/pending': typeof AuthenticatedReviewsPendingRoute
  '/security/activity': typeof AuthenticatedSecurityActivityRoute
  '/security/roles': typeof AuthenticatedSecurityRolesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/content': typeof AuthenticatedSettingsContentRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/seo': typeof AuthenticatedSettingsSeoRoute
  '/settings/social': typeof AuthenticatedSettingsSocialRoute
  '/tour-packages/categories': typeof AuthenticatedTourPackagesCategoriesRoute
  '/tour-packages/itineraries': typeof AuthenticatedTourPackagesItinerariesRoute
  '/tour-packages/new': typeof AuthenticatedTourPackagesNewRoute
  '/users/customers': typeof AuthenticatedUsersCustomersRoute
  '/users/staff': typeof AuthenticatedUsersStaffRoute
  '/users/tour-guides': typeof AuthenticatedUsersTourGuidesRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/blog': typeof AuthenticatedBlogIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/car-rental': typeof AuthenticatedCarRentalIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/destinations': typeof AuthenticatedDestinationsIndexRoute
  '/gallery': typeof AuthenticatedGalleryIndexRoute
  '/guides': typeof AuthenticatedGuidesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tour-packages': typeof AuthenticatedTourPackagesIndexRoute
  '/tracking': typeof AuthenticatedTrackingIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/car-rental/vehicles/$vehicleId': typeof AuthenticatedCarRentalVehiclesVehicleIdRoute
  '/car-rental/vehicles/new': typeof AuthenticatedCarRentalVehiclesNewRoute
  '/car-rental/vehicles': typeof AuthenticatedCarRentalVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/blog/categories': typeof AuthenticatedBlogCategoriesRoute
  '/_authenticated/blog/new': typeof AuthenticatedBlogNewRoute
  '/_authenticated/bookings/cancelled': typeof AuthenticatedBookingsCancelledRoute
  '/_authenticated/bookings/confirmed': typeof AuthenticatedBookingsConfirmedRoute
  '/_authenticated/bookings/pending': typeof AuthenticatedBookingsPendingRoute
  '/_authenticated/car-rental/pending': typeof AuthenticatedCarRentalPendingRoute
  '/_authenticated/destinations/new': typeof AuthenticatedDestinationsNewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/gallery/upload': typeof AuthenticatedGalleryUploadRoute
  '/_authenticated/guides/assign': typeof AuthenticatedGuidesAssignRoute
  '/_authenticated/guides/availability': typeof AuthenticatedGuidesAvailabilityRoute
  '/_authenticated/messages/contact': typeof AuthenticatedMessagesContactRoute
  '/_authenticated/messages/inquiries': typeof AuthenticatedMessagesInquiriesRoute
  '/_authenticated/payments/refunds': typeof AuthenticatedPaymentsRefundsRoute
  '/_authenticated/payments/status': typeof AuthenticatedPaymentsStatusRoute
  '/_authenticated/payments/transactions': typeof AuthenticatedPaymentsTransactionsRoute
  '/_authenticated/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/_authenticated/reports/bookings': typeof AuthenticatedReportsBookingsRoute
  '/_authenticated/reports/revenue': typeof AuthenticatedReportsRevenueRoute
  '/_authenticated/reviews/pending': typeof AuthenticatedReviewsPendingRoute
  '/_authenticated/security/activity': typeof AuthenticatedSecurityActivityRoute
  '/_authenticated/security/roles': typeof AuthenticatedSecurityRolesRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/content': typeof AuthenticatedSettingsContentRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/seo': typeof AuthenticatedSettingsSeoRoute
  '/_authenticated/settings/social': typeof AuthenticatedSettingsSocialRoute
  '/_authenticated/tour-packages/categories': typeof AuthenticatedTourPackagesCategoriesRoute
  '/_authenticated/tour-packages/itineraries': typeof AuthenticatedTourPackagesItinerariesRoute
  '/_authenticated/tour-packages/new': typeof AuthenticatedTourPackagesNewRoute
  '/_authenticated/users/customers': typeof AuthenticatedUsersCustomersRoute
  '/_authenticated/users/staff': typeof AuthenticatedUsersStaffRoute
  '/_authenticated/users/tour-guides': typeof AuthenticatedUsersTourGuidesRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/blog/': typeof AuthenticatedBlogIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/car-rental/': typeof AuthenticatedCarRentalIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/_authenticated/gallery/': typeof AuthenticatedGalleryIndexRoute
  '/_authenticated/guides/': typeof AuthenticatedGuidesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tour-packages/': typeof AuthenticatedTourPackagesIndexRoute
  '/_authenticated/tracking/': typeof AuthenticatedTrackingIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/car-rental/vehicles/$vehicleId': typeof AuthenticatedCarRentalVehiclesVehicleIdRoute
  '/_authenticated/car-rental/vehicles/new': typeof AuthenticatedCarRentalVehiclesNewRoute
  '/_authenticated/car-rental/vehicles/': typeof AuthenticatedCarRentalVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/$'
    | '/blog/categories'
    | '/blog/new'
    | '/bookings/cancelled'
    | '/bookings/confirmed'
    | '/bookings/pending'
    | '/car-rental/pending'
    | '/destinations/new'
    | '/errors/$error'
    | '/gallery/upload'
    | '/guides/assign'
    | '/guides/availability'
    | '/messages/contact'
    | '/messages/inquiries'
    | '/payments/refunds'
    | '/payments/status'
    | '/payments/transactions'
    | '/reports/analytics'
    | '/reports/bookings'
    | '/reports/revenue'
    | '/reviews/pending'
    | '/security/activity'
    | '/security/roles'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/content'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/seo'
    | '/settings/social'
    | '/tour-packages/categories'
    | '/tour-packages/itineraries'
    | '/tour-packages/new'
    | '/users/customers'
    | '/users/staff'
    | '/users/tour-guides'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/blog/'
    | '/bookings/'
    | '/calendar/'
    | '/car-rental/'
    | '/chats/'
    | '/destinations/'
    | '/gallery/'
    | '/guides/'
    | '/help-center/'
    | '/notifications/'
    | '/reviews/'
    | '/settings/'
    | '/tasks/'
    | '/tour-packages/'
    | '/tracking/'
    | '/users/'
    | '/car-rental/vehicles/$vehicleId'
    | '/car-rental/vehicles/new'
    | '/car-rental/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/$'
    | '/'
    | '/blog/categories'
    | '/blog/new'
    | '/bookings/cancelled'
    | '/bookings/confirmed'
    | '/bookings/pending'
    | '/car-rental/pending'
    | '/destinations/new'
    | '/errors/$error'
    | '/gallery/upload'
    | '/guides/assign'
    | '/guides/availability'
    | '/messages/contact'
    | '/messages/inquiries'
    | '/payments/refunds'
    | '/payments/status'
    | '/payments/transactions'
    | '/reports/analytics'
    | '/reports/bookings'
    | '/reports/revenue'
    | '/reviews/pending'
    | '/security/activity'
    | '/security/roles'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/content'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/seo'
    | '/settings/social'
    | '/tour-packages/categories'
    | '/tour-packages/itineraries'
    | '/tour-packages/new'
    | '/users/customers'
    | '/users/staff'
    | '/users/tour-guides'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/blog'
    | '/bookings'
    | '/calendar'
    | '/car-rental'
    | '/chats'
    | '/destinations'
    | '/gallery'
    | '/guides'
    | '/help-center'
    | '/notifications'
    | '/reviews'
    | '/settings'
    | '/tasks'
    | '/tour-packages'
    | '/tracking'
    | '/users'
    | '/car-rental/vehicles/$vehicleId'
    | '/car-rental/vehicles/new'
    | '/car-rental/vehicles'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/$'
    | '/_authenticated/'
    | '/_authenticated/blog/categories'
    | '/_authenticated/blog/new'
    | '/_authenticated/bookings/cancelled'
    | '/_authenticated/bookings/confirmed'
    | '/_authenticated/bookings/pending'
    | '/_authenticated/car-rental/pending'
    | '/_authenticated/destinations/new'
    | '/_authenticated/errors/$error'
    | '/_authenticated/gallery/upload'
    | '/_authenticated/guides/assign'
    | '/_authenticated/guides/availability'
    | '/_authenticated/messages/contact'
    | '/_authenticated/messages/inquiries'
    | '/_authenticated/payments/refunds'
    | '/_authenticated/payments/status'
    | '/_authenticated/payments/transactions'
    | '/_authenticated/reports/analytics'
    | '/_authenticated/reports/bookings'
    | '/_authenticated/reports/revenue'
    | '/_authenticated/reviews/pending'
    | '/_authenticated/security/activity'
    | '/_authenticated/security/roles'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/content'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/seo'
    | '/_authenticated/settings/social'
    | '/_authenticated/tour-packages/categories'
    | '/_authenticated/tour-packages/itineraries'
    | '/_authenticated/tour-packages/new'
    | '/_authenticated/users/customers'
    | '/_authenticated/users/staff'
    | '/_authenticated/users/tour-guides'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/blog/'
    | '/_authenticated/bookings/'
    | '/_authenticated/calendar/'
    | '/_authenticated/car-rental/'
    | '/_authenticated/chats/'
    | '/_authenticated/destinations/'
    | '/_authenticated/gallery/'
    | '/_authenticated/guides/'
    | '/_authenticated/help-center/'
    | '/_authenticated/notifications/'
    | '/_authenticated/reviews/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tour-packages/'
    | '/_authenticated/tracking/'
    | '/_authenticated/users/'
    | '/_authenticated/car-rental/vehicles/$vehicleId'
    | '/_authenticated/car-rental/vehicles/new'
    | '/_authenticated/car-rental/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracking/': {
      id: '/_authenticated/tracking/'
      path: '/tracking'
      fullPath: '/tracking/'
      preLoaderRoute: typeof AuthenticatedTrackingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour-packages/': {
      id: '/_authenticated/tour-packages/'
      path: '/tour-packages'
      fullPath: '/tour-packages/'
      preLoaderRoute: typeof AuthenticatedTourPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reviews/': {
      id: '/_authenticated/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthenticatedReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guides/': {
      id: '/_authenticated/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof AuthenticatedGuidesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery/': {
      id: '/_authenticated/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof AuthenticatedGalleryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destinations/': {
      id: '/_authenticated/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof AuthenticatedDestinationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-rental/': {
      id: '/_authenticated/car-rental/'
      path: '/car-rental'
      fullPath: '/car-rental/'
      preLoaderRoute: typeof AuthenticatedCarRentalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog/': {
      id: '/_authenticated/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof AuthenticatedBlogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/users/tour-guides': {
      id: '/_authenticated/users/tour-guides'
      path: '/users/tour-guides'
      fullPath: '/users/tour-guides'
      preLoaderRoute: typeof AuthenticatedUsersTourGuidesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/staff': {
      id: '/_authenticated/users/staff'
      path: '/users/staff'
      fullPath: '/users/staff'
      preLoaderRoute: typeof AuthenticatedUsersStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/customers': {
      id: '/_authenticated/users/customers'
      path: '/users/customers'
      fullPath: '/users/customers'
      preLoaderRoute: typeof AuthenticatedUsersCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour-packages/new': {
      id: '/_authenticated/tour-packages/new'
      path: '/tour-packages/new'
      fullPath: '/tour-packages/new'
      preLoaderRoute: typeof AuthenticatedTourPackagesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour-packages/itineraries': {
      id: '/_authenticated/tour-packages/itineraries'
      path: '/tour-packages/itineraries'
      fullPath: '/tour-packages/itineraries'
      preLoaderRoute: typeof AuthenticatedTourPackagesItinerariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour-packages/categories': {
      id: '/_authenticated/tour-packages/categories'
      path: '/tour-packages/categories'
      fullPath: '/tour-packages/categories'
      preLoaderRoute: typeof AuthenticatedTourPackagesCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/social': {
      id: '/_authenticated/settings/social'
      path: '/social'
      fullPath: '/settings/social'
      preLoaderRoute: typeof AuthenticatedSettingsSocialRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/seo': {
      id: '/_authenticated/settings/seo'
      path: '/seo'
      fullPath: '/settings/seo'
      preLoaderRoute: typeof AuthenticatedSettingsSeoRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/content': {
      id: '/_authenticated/settings/content'
      path: '/content'
      fullPath: '/settings/content'
      preLoaderRoute: typeof AuthenticatedSettingsContentRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/security/roles': {
      id: '/_authenticated/security/roles'
      path: '/security/roles'
      fullPath: '/security/roles'
      preLoaderRoute: typeof AuthenticatedSecurityRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/activity': {
      id: '/_authenticated/security/activity'
      path: '/security/activity'
      fullPath: '/security/activity'
      preLoaderRoute: typeof AuthenticatedSecurityActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews/pending': {
      id: '/_authenticated/reviews/pending'
      path: '/reviews/pending'
      fullPath: '/reviews/pending'
      preLoaderRoute: typeof AuthenticatedReviewsPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/revenue': {
      id: '/_authenticated/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/reports/revenue'
      preLoaderRoute: typeof AuthenticatedReportsRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/bookings': {
      id: '/_authenticated/reports/bookings'
      path: '/reports/bookings'
      fullPath: '/reports/bookings'
      preLoaderRoute: typeof AuthenticatedReportsBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/analytics': {
      id: '/_authenticated/reports/analytics'
      path: '/reports/analytics'
      fullPath: '/reports/analytics'
      preLoaderRoute: typeof AuthenticatedReportsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/transactions': {
      id: '/_authenticated/payments/transactions'
      path: '/payments/transactions'
      fullPath: '/payments/transactions'
      preLoaderRoute: typeof AuthenticatedPaymentsTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/status': {
      id: '/_authenticated/payments/status'
      path: '/payments/status'
      fullPath: '/payments/status'
      preLoaderRoute: typeof AuthenticatedPaymentsStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/refunds': {
      id: '/_authenticated/payments/refunds'
      path: '/payments/refunds'
      fullPath: '/payments/refunds'
      preLoaderRoute: typeof AuthenticatedPaymentsRefundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/inquiries': {
      id: '/_authenticated/messages/inquiries'
      path: '/messages/inquiries'
      fullPath: '/messages/inquiries'
      preLoaderRoute: typeof AuthenticatedMessagesInquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/contact': {
      id: '/_authenticated/messages/contact'
      path: '/messages/contact'
      fullPath: '/messages/contact'
      preLoaderRoute: typeof AuthenticatedMessagesContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guides/availability': {
      id: '/_authenticated/guides/availability'
      path: '/guides/availability'
      fullPath: '/guides/availability'
      preLoaderRoute: typeof AuthenticatedGuidesAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guides/assign': {
      id: '/_authenticated/guides/assign'
      path: '/guides/assign'
      fullPath: '/guides/assign'
      preLoaderRoute: typeof AuthenticatedGuidesAssignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery/upload': {
      id: '/_authenticated/gallery/upload'
      path: '/gallery/upload'
      fullPath: '/gallery/upload'
      preLoaderRoute: typeof AuthenticatedGalleryUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/destinations/new': {
      id: '/_authenticated/destinations/new'
      path: '/destinations/new'
      fullPath: '/destinations/new'
      preLoaderRoute: typeof AuthenticatedDestinationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-rental/pending': {
      id: '/_authenticated/car-rental/pending'
      path: '/car-rental/pending'
      fullPath: '/car-rental/pending'
      preLoaderRoute: typeof AuthenticatedCarRentalPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/pending': {
      id: '/_authenticated/bookings/pending'
      path: '/bookings/pending'
      fullPath: '/bookings/pending'
      preLoaderRoute: typeof AuthenticatedBookingsPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/confirmed': {
      id: '/_authenticated/bookings/confirmed'
      path: '/bookings/confirmed'
      fullPath: '/bookings/confirmed'
      preLoaderRoute: typeof AuthenticatedBookingsConfirmedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/cancelled': {
      id: '/_authenticated/bookings/cancelled'
      path: '/bookings/cancelled'
      fullPath: '/bookings/cancelled'
      preLoaderRoute: typeof AuthenticatedBookingsCancelledRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog/new': {
      id: '/_authenticated/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof AuthenticatedBlogNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog/categories': {
      id: '/_authenticated/blog/categories'
      path: '/blog/categories'
      fullPath: '/blog/categories'
      preLoaderRoute: typeof AuthenticatedBlogCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-rental/vehicles/': {
      id: '/_authenticated/car-rental/vehicles/'
      path: '/car-rental/vehicles'
      fullPath: '/car-rental/vehicles/'
      preLoaderRoute: typeof AuthenticatedCarRentalVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-rental/vehicles/new': {
      id: '/_authenticated/car-rental/vehicles/new'
      path: '/car-rental/vehicles/new'
      fullPath: '/car-rental/vehicles/new'
      preLoaderRoute: typeof AuthenticatedCarRentalVehiclesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-rental/vehicles/$vehicleId': {
      id: '/_authenticated/car-rental/vehicles/$vehicleId'
      path: '/car-rental/vehicles/$vehicleId'
      fullPath: '/car-rental/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthenticatedCarRentalVehiclesVehicleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsContentRoute: typeof AuthenticatedSettingsContentRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsSeoRoute: typeof AuthenticatedSettingsSeoRoute
  AuthenticatedSettingsSocialRoute: typeof AuthenticatedSettingsSocialRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsContentRoute: AuthenticatedSettingsContentRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsSeoRoute: AuthenticatedSettingsSeoRoute,
    AuthenticatedSettingsSocialRoute: AuthenticatedSettingsSocialRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBlogCategoriesRoute: typeof AuthenticatedBlogCategoriesRoute
  AuthenticatedBlogNewRoute: typeof AuthenticatedBlogNewRoute
  AuthenticatedBookingsCancelledRoute: typeof AuthenticatedBookingsCancelledRoute
  AuthenticatedBookingsConfirmedRoute: typeof AuthenticatedBookingsConfirmedRoute
  AuthenticatedBookingsPendingRoute: typeof AuthenticatedBookingsPendingRoute
  AuthenticatedCarRentalPendingRoute: typeof AuthenticatedCarRentalPendingRoute
  AuthenticatedDestinationsNewRoute: typeof AuthenticatedDestinationsNewRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedGalleryUploadRoute: typeof AuthenticatedGalleryUploadRoute
  AuthenticatedGuidesAssignRoute: typeof AuthenticatedGuidesAssignRoute
  AuthenticatedGuidesAvailabilityRoute: typeof AuthenticatedGuidesAvailabilityRoute
  AuthenticatedMessagesContactRoute: typeof AuthenticatedMessagesContactRoute
  AuthenticatedMessagesInquiriesRoute: typeof AuthenticatedMessagesInquiriesRoute
  AuthenticatedPaymentsRefundsRoute: typeof AuthenticatedPaymentsRefundsRoute
  AuthenticatedPaymentsStatusRoute: typeof AuthenticatedPaymentsStatusRoute
  AuthenticatedPaymentsTransactionsRoute: typeof AuthenticatedPaymentsTransactionsRoute
  AuthenticatedReportsAnalyticsRoute: typeof AuthenticatedReportsAnalyticsRoute
  AuthenticatedReportsBookingsRoute: typeof AuthenticatedReportsBookingsRoute
  AuthenticatedReportsRevenueRoute: typeof AuthenticatedReportsRevenueRoute
  AuthenticatedReviewsPendingRoute: typeof AuthenticatedReviewsPendingRoute
  AuthenticatedSecurityActivityRoute: typeof AuthenticatedSecurityActivityRoute
  AuthenticatedSecurityRolesRoute: typeof AuthenticatedSecurityRolesRoute
  AuthenticatedTourPackagesCategoriesRoute: typeof AuthenticatedTourPackagesCategoriesRoute
  AuthenticatedTourPackagesItinerariesRoute: typeof AuthenticatedTourPackagesItinerariesRoute
  AuthenticatedTourPackagesNewRoute: typeof AuthenticatedTourPackagesNewRoute
  AuthenticatedUsersCustomersRoute: typeof AuthenticatedUsersCustomersRoute
  AuthenticatedUsersStaffRoute: typeof AuthenticatedUsersStaffRoute
  AuthenticatedUsersTourGuidesRoute: typeof AuthenticatedUsersTourGuidesRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBlogIndexRoute: typeof AuthenticatedBlogIndexRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedCarRentalIndexRoute: typeof AuthenticatedCarRentalIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDestinationsIndexRoute: typeof AuthenticatedDestinationsIndexRoute
  AuthenticatedGalleryIndexRoute: typeof AuthenticatedGalleryIndexRoute
  AuthenticatedGuidesIndexRoute: typeof AuthenticatedGuidesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedReviewsIndexRoute: typeof AuthenticatedReviewsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTourPackagesIndexRoute: typeof AuthenticatedTourPackagesIndexRoute
  AuthenticatedTrackingIndexRoute: typeof AuthenticatedTrackingIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedCarRentalVehiclesVehicleIdRoute: typeof AuthenticatedCarRentalVehiclesVehicleIdRoute
  AuthenticatedCarRentalVehiclesNewRoute: typeof AuthenticatedCarRentalVehiclesNewRoute
  AuthenticatedCarRentalVehiclesIndexRoute: typeof AuthenticatedCarRentalVehiclesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBlogCategoriesRoute: AuthenticatedBlogCategoriesRoute,
  AuthenticatedBlogNewRoute: AuthenticatedBlogNewRoute,
  AuthenticatedBookingsCancelledRoute: AuthenticatedBookingsCancelledRoute,
  AuthenticatedBookingsConfirmedRoute: AuthenticatedBookingsConfirmedRoute,
  AuthenticatedBookingsPendingRoute: AuthenticatedBookingsPendingRoute,
  AuthenticatedCarRentalPendingRoute: AuthenticatedCarRentalPendingRoute,
  AuthenticatedDestinationsNewRoute: AuthenticatedDestinationsNewRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedGalleryUploadRoute: AuthenticatedGalleryUploadRoute,
  AuthenticatedGuidesAssignRoute: AuthenticatedGuidesAssignRoute,
  AuthenticatedGuidesAvailabilityRoute: AuthenticatedGuidesAvailabilityRoute,
  AuthenticatedMessagesContactRoute: AuthenticatedMessagesContactRoute,
  AuthenticatedMessagesInquiriesRoute: AuthenticatedMessagesInquiriesRoute,
  AuthenticatedPaymentsRefundsRoute: AuthenticatedPaymentsRefundsRoute,
  AuthenticatedPaymentsStatusRoute: AuthenticatedPaymentsStatusRoute,
  AuthenticatedPaymentsTransactionsRoute:
    AuthenticatedPaymentsTransactionsRoute,
  AuthenticatedReportsAnalyticsRoute: AuthenticatedReportsAnalyticsRoute,
  AuthenticatedReportsBookingsRoute: AuthenticatedReportsBookingsRoute,
  AuthenticatedReportsRevenueRoute: AuthenticatedReportsRevenueRoute,
  AuthenticatedReviewsPendingRoute: AuthenticatedReviewsPendingRoute,
  AuthenticatedSecurityActivityRoute: AuthenticatedSecurityActivityRoute,
  AuthenticatedSecurityRolesRoute: AuthenticatedSecurityRolesRoute,
  AuthenticatedTourPackagesCategoriesRoute:
    AuthenticatedTourPackagesCategoriesRoute,
  AuthenticatedTourPackagesItinerariesRoute:
    AuthenticatedTourPackagesItinerariesRoute,
  AuthenticatedTourPackagesNewRoute: AuthenticatedTourPackagesNewRoute,
  AuthenticatedUsersCustomersRoute: AuthenticatedUsersCustomersRoute,
  AuthenticatedUsersStaffRoute: AuthenticatedUsersStaffRoute,
  AuthenticatedUsersTourGuidesRoute: AuthenticatedUsersTourGuidesRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBlogIndexRoute: AuthenticatedBlogIndexRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedCarRentalIndexRoute: AuthenticatedCarRentalIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDestinationsIndexRoute: AuthenticatedDestinationsIndexRoute,
  AuthenticatedGalleryIndexRoute: AuthenticatedGalleryIndexRoute,
  AuthenticatedGuidesIndexRoute: AuthenticatedGuidesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedReviewsIndexRoute: AuthenticatedReviewsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTourPackagesIndexRoute: AuthenticatedTourPackagesIndexRoute,
  AuthenticatedTrackingIndexRoute: AuthenticatedTrackingIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedCarRentalVehiclesVehicleIdRoute:
    AuthenticatedCarRentalVehiclesVehicleIdRoute,
  AuthenticatedCarRentalVehiclesNewRoute:
    AuthenticatedCarRentalVehiclesNewRoute,
  AuthenticatedCarRentalVehiclesIndexRoute:
    AuthenticatedCarRentalVehiclesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
